# Generated by Django 2.2.16 on 2020-10-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='Untitled', max_length=240),
        ),
    ]
